    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jcsp0003
 */
public class TablaJFrame extends javax.swing.JFrame {

    private final DefaultTableModel modelo;
    private final String tipo;

    /**
     * Creates new form TablaJFrame
     *
     * @param tipoo
     */
    public TablaJFrame(String tipoo) {
        initComponents();
        this.setVisible(true);
        this.tipo = tipoo;
        this.setTitle("Tabla de " + this.tipo);

        modelo = new DefaultTableModel();
        if ("Agricultor".equals(this.tipo)) {
            modelo.addColumn("Agentes agricultor");
            modelo.addColumn("Ganancias");
        } else {
            modelo.addColumn("Agentes mercado");
            modelo.addColumn("Stocks");
            setLocation(440, 0);
        }
        this.tabla.setModel(modelo);
    }

    public void insertarFila(String nombreAgente, String valor) {
        int filas = modelo.getRowCount();
        for (int i = 0; i < filas; i++) {
            if (modelo.getValueAt(i, 0).toString().equals(nombreAgente)) {
                modelo.setValueAt(valor, i, 1);
                return;
            }
        }
        String[] Datos = new String[2];
        Datos[0] = nombreAgente;
        Datos[1] = valor;
        modelo.addRow(Datos);
    }

    public void burbuja() {
        int nFilas = modelo.getRowCount();
        String auxNombre, auxValor;
        int v1, v2;
        for (int i = 0; i < nFilas - 1; i++) {
            for (int j = 0; j < nFilas - i - 1; j++) {
                v1 = Integer.parseInt(modelo.getValueAt(j + 1, 1).toString());
                v2 = Integer.parseInt(modelo.getValueAt(j, 1).toString());
                if (v1 > v2) {
                    auxNombre = modelo.getValueAt(j + 1, 0).toString();
                    auxValor = modelo.getValueAt(j + 1, 1).toString();
                    modelo.setValueAt(modelo.getValueAt(j, 0).toString(), j + 1, 0);
                    modelo.setValueAt(modelo.getValueAt(j, 1).toString(), j + 1, 1);
                    modelo.setValueAt(auxNombre, j, 0);
                    modelo.setValueAt(auxValor, j, 1);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
